- hosts: vps
  become: yes
  tasks:
    - name: Send webhook to mark start of deployment
      uri:
        url: "{{ webhook }}"
        method: POST
        body_format: json
        status_code: 204
        body:
          content: ":inbox_tray: Deployment process starting for Image Man, updating from GitHub."

    - name: Pull from GitHub
      git:
        repo: git@github.com:jos-b/image-man.git
        dest: /opt/image-man
        key_file: /home/joseph/.ssh/id_rsa

    - name: Copy config file to project
      copy:
        src: /Users/joseph/image-man/config.yaml
        dest: /opt/image-man/config.yaml

    - name: Ensure apt dependencies are installed
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - libmagickwand-dev

    - name: Ensure requirements are installed
      pip:
        requirements: /opt/image-man/requirements.txt
        state: present
        virtualenv: /opt/image-man/venv
        virtualenv_python: /home/joseph/.pyenv/shims/python3.7

    - name: Ensure the systemd service is up-to-date
      template:
        src: image-man.service.j2
        dest: /etc/systemd/system/image-man.service
        owner: root
        group: root
        mode: 0444

    - name: ensure the service is started
      systemd:
        daemon_reload: true
        name: image-man.service
        state: started
        enabled: true

    - name: Send webhook message to notify of deployment
      uri:
        url: "{{ webhook }}"
        method: POST
        body_format: json
        status_code: 204
        body:
          content: ":ok_hand: Image man has been deployed."
